export const PROJECTS_GET_REQUEST = 'PROJECTS_GET_REQUEST';
export const PROJECTS_GET_SUCCESS = 'PROJECTS_GET_SUCCESS';
export const PROJECTS_GET_FAILURE = 'PROJECTS_GET_FAILURE';

export const PROJECT_SAVE_REQUEST = 'PROJECT_SAVE_REQUEST';
export const PROJECT_SAVE_SUCCESS = 'PROJECT_SAVE_SUCCESS';
export const PROJECT_SAVE_FAILURE = 'PROJECT_SAVE_FAILURE';

export const PROJECT_DETAILS_REQUEST = 'PROJECT_DETAILS_REQUEST';
export const PROJECT_DETAILS_SUCCESS = 'PROJECT_DETAILS_SUCCESS';
export const PROJECT_DETAILS_FAILURE = 'PROJECT_DETAILS_FAILURE';

export const PROJECT_DELETE_REQUEST = 'PROJECT_DELETE_REQUEST';
export const PROJECT_DELETE_SUCCESS = 'PROJECT_DELETE_SUCCESS';
export const PROJECT_DELETE_FAILURE = 'PROJECT_DELETE_FAILURE';

export const USERS_IN_PROJECT_REQUEST = 'USERS_IN_PROJECT_REQUEST';
export const USERS_IN_PROJECT_SUCCESS = 'USERS_IN_PROJECT_SUCCESS';
export const USERS_IN_PROJECT_FAILURE = 'USERS_IN_PROJECT_FAILURE';

export const USER_IN_PROJECT_SAVE_REQUEST = 'USER_IN_PROJECT_SAVE_REQUEST';
export const USER_IN_PROJECT_SAVE_SUCCESS = 'USER_IN_PROJECT_SAVE_SUCCESS';
export const USER_IN_PROJECT_SAVE_FAILURE = 'USER_IN_PROJECT_SAVE_FAILURE';