export const TASKS_GET_REQUEST = 'TASKS_GET_REQUEST';
export const TASKS_GET_SUCCESS = 'TASKS_GET_SUCCESS';
export const TASKS_GET_FAILURE = 'TASKS_GET_FAILURE';

export const USER_TASKS_GET_REQUEST = 'USER_TASKS_GET_REQUEST';
export const USER_TASKS_GET_SUCCESS = 'USER_TASKS_GET_SUCCESS';
export const USER_TASKS_GET_FAILURE = 'USER_TASKS_GET_FAILURE';

export const TASK_SAVE_REQUEST = 'TASK_SAVE_REQUEST';
export const TASK_SAVE_SUCCESS = 'TASK_SAVE_SUCCESS';
export const TASK_SAVE_FAILURE = 'TASK_SAVE_FAILURE';

export const TASK_DETAILS_REQUEST = 'TASK_DETAILS_REQUEST';
export const TASK_DETAILS_SUCCESS = 'TASK_DETAILS_SUCCESS';
export const TASK_DETAILS_FAILURE = 'TASK_DETAILS_FAILURE';

export const TASK_DELETE_REQUEST = 'TASK_DELETE_REQUEST';
export const TASK_DELETE_SUCCESS = 'TASK_DELETE_SUCCESS';
export const TASK_DELETE_FAILURE = 'TASK_DELETE_FAILURE';